<?php
/** @var TIG_TinyPNG_Block_Adminhtml_System_Config_Form_Field_SupportTab $this */
?>

<?php $_tigHomepage             = 'https://tig.nl/tinypng-magento-extensie-community-edition/'; ?>
<?php $_kbUrl                   = 'http://servicedesk.tig.nl/hc/nl/categories/202720888-TinyPNG'; ?>
<?php $_kbTicketUrl             = 'http://servicedesk.tig.nl/hc/nl/requests/new'; ?>
<?php $_changelogUrl            = 'https://tig.nl'; ?>
<?php $_installationManualUrl   = 'http://servicedesk.tig.nl/hc/nl/articles/219422177-TinyPNG-handleiding'; ?>
<?php $_userGuideUrl            = 'https://tig.nl'; ?>
<?php $_version                 = $this->getModuleVersion(); ?>
<?php $_stability               = $this->getModuleStability(); ?>

<tr id="tig_tinypng_support">
    <td>
        <h2 class="content-heading">
            <?php echo $this->__('Image Optimization');?>
            <?php if (!empty($_stability) && $_stability != 'stable'): ?>
                - <?php echo $_stability; ?>
            <?php endif; ?>
        </h2>
        <table id="supportWrap" cellpadding="0" cellspacing="0">
            <tr>
                <td colspan="2">

                    <div class="">
                        <div class="col-set">
                            <div class="col-1">
                                <p>
                                    <?php echo $this->__('Make your store faster by optimizing your JPEG and PNG product images. This extension automatically optimizes the images by integrating with the popular image compression services TinyJPG and TinyPNG.'); ?>
                                </p>

                                <!-- Magento CE -->
                                <?php if (Mage::getEdition() === 'Community'): ?>
                                    <p>
                                        <?php echo $this->__('In case you need help or assistance with the extension or your account please contact'); ?> <a href="mailto:support@tinypng.com">support@tinypng.com</a>.
                                    </p>
                                <?php else: ?>
                                    <!-- Magento EE -->
                                    <p>
                                        <?php echo $this->__('For general questions and help with your account please contact') ?> <a href="mailto:support@tinypng.com">support@tinypng.com</a>.
                                    </p>
                                <?php endif; ?>

                                <p>
                                    <?php echo $this->__('For technical questions and developer support please contact the extension developer through the special'); ?> <a target="_blank" href="<?php echo $_kbTicketUrl; ?>"><?php echo $this->__('support website'); ?></a>.
                                </p>

                                <div class="tig_branding">
                                    <div class="signature">
                                        <p>
                                            <?php echo $this->__('The extension is developed by TIG.');?> <br />
                                            <?php echo $this->__('Visit our website:'); ?> <a target="_blank" href="<?php echo $_tigHomepage ?>" class=""><?php echo $this->__('TIG.nl');?></a>
                                        </p>
                                    </div>

                                </div>

                            </div>
                            <div class="col-2">
                                <img class="tiny-logo-bear" alt="TinyPNG" src="<?php echo $this->getSkinUrl('images/TIG/TinyPNG/george-magento@2x_opt.png'); ?>" />
                            </div>
                        </div>
                    </div>

                </td>
            </tr>
        </table>
    </td>
</tr>

<script>
    //<![CDATA[
    // Remove default onclick value
    $('tig_tinypng_support-head').setAttribute('onclick', '');
    // Get and remove the first head on the page (ours)
    $$('.entry-edit-head')[0].remove();
    // Set tabs open.
    document.observe('dom:loaded', function() {
        $('tig_tinypng_image_types').setStyle({display: 'block'});
        $('tig_tinypng_status').setStyle({display: 'block'});
        $('tig_tinypng_settings').setStyle({display: 'block'});
    });
    //]]>
</script>
