<tr id="row_tiny_compressimages_advanced_log_file">
    <td class="label">
        <label for="tiny_compressimages_advanced_log_file"> Log file</label>
    </td>
    <td class="value">
        <button onclick="setLocation('<?php echo $this->getDownloadUrl(); ?>')" type="button" class="scalable">
            <span><span><span><?php echo $this->__('Download log file'); ?></span></span></span>
        </button>
    </td>
</tr>


