<?php
/**
 * @var TIG_TinyPNG_Block_Adminhtml_Cache_Warning $this
 */
$helper = Mage::helper('tig_tinypng');
$configHelper = Mage::helper('tig_tinypng/config');

$message = 'Note: When flushing the image cache, the TinyPNG extension will re-optimize all product images that ' .
    'are shown on the store view(s).';

if ($configHelper->isConfigured()):
?>
<script type="text/javascript">
document.observe('dom:loaded', function () {
    var element = $$('[onclick*="<?php echo $this->getCleanImagesUrl(); ?>"]');
    var link = $(element[0]);

    /**
     * Remove the default onclick handler, we cannot override it.
     */
    link.onclick = null;

    link.observe('click', function (e) {
        if (confirm('<?php echo $helper->__($message); ?>')) {
            location.href = '<?php echo $this->getCleanImagesUrl(); ?>';
        }
    });
});
</script>
<?php endif; ?>
